version: 1

jobs:
  build:
    steps:
      - name: Checkout Code
        action: probo/action/checkout
      
      - name: Run GitHub Actions Workflow
        action: probo/github-action
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          workflow-file: .github/workflows/rdp.yml
